import * as fs from 'fs';
import * as path from 'path';

/**
 * Default patterns that should ALWAYS be ignored in Syncthing
 * This prevents Syncthing from conflicting with Git
 */
export const DEFAULT_STIGNORE_PATTERNS = [
    '.git',
    '.gitignore',
    'node_modules',
    '.DS_Store',
    'Thumbs.db',
    '*.sync-conflict-*' // Don't sync conflict files themselves
];

/**
 * Parse .gitignore file and return array of patterns
 */
export async function parseGitignore(folderPath: string): Promise<string[]> {
    const gitignorePath = path.join(folderPath, '.gitignore');

    try {
        const content = await fs.promises.readFile(gitignorePath, 'utf-8');
        return content
            .split('\n')
            .map(line => line.trim())
            .filter(line => line && !line.startsWith('#')); // Remove empty lines and comments
    } catch {
        return [];
    }
}

/**
 * Convert gitignore patterns to stignore format
 * Syncthing's .stignore is similar to .gitignore but with some differences
 */
export function convertToStignore(patterns: string[]): string[] {
    return patterns
        .filter(p => !p.startsWith('!')) // Remove negation patterns (not supported by stignore)
        .map(pattern => {
            // Ensure directory patterns end with /
            // Most patterns work the same between gitignore and stignore
            return pattern;
        });
}

/**
 * Read existing .stignore file
 */
export async function getStignore(folderPath: string): Promise<string[]> {
    const stignorePath = path.join(folderPath, '.stignore');

    try {
        const content = await fs.promises.readFile(stignorePath, 'utf-8');
        return content
            .split('\n')
            .map(line => line.trim())
            .filter(line => line && !line.startsWith('//')); // Remove comments
    } catch {
        return [];
    }
}

/**
 * Write patterns to .stignore file
 */
export async function writeStignore(folderPath: string, patterns: string[]): Promise<void> {
    const stignorePath = path.join(folderPath, '.stignore');
    const header = '// Auto-generated by SyncMaster\n// https://docs.syncthing.net/users/ignoring.html\n\n';
    const content = header + patterns.join('\n') + '\n';

    await fs.promises.writeFile(stignorePath, content, 'utf-8');
}

/**
 * Merge gitignore patterns into stignore (without duplicates)
 * Always includes DEFAULT_STIGNORE_PATTERNS to prevent Git/Syncthing conflicts
 */
export async function mergeIgnores(folderPath: string, additionalPatterns: string[]): Promise<string[]> {
    const existing = await getStignore(folderPath);
    const converted = convertToStignore(additionalPatterns);

    // Combine defaults + existing + new, then dedupe
    const combined = [...new Set([...DEFAULT_STIGNORE_PATTERNS, ...existing, ...converted])];

    await writeStignore(folderPath, combined);
    return combined;
}

/**
 * Import gitignore into stignore for a folder
 */
export async function importGitignore(folderPath: string): Promise<{ imported: number; total: number }> {
    const gitPatterns = await parseGitignore(folderPath);

    if (gitPatterns.length === 0) {
        return { imported: 0, total: 0 };
    }

    const merged = await mergeIgnores(folderPath, gitPatterns);
    return { imported: gitPatterns.length, total: merged.length };
}

/**
 * Apply profile default ignores to a folder
 * This REPLACES user patterns (not merges) so removals work correctly
 */
export async function applyProfileIgnores(folderPath: string, patterns: string[]): Promise<{ applied: number; total: number }> {
    // Always include defaults + the new user patterns
    // Do NOT merge with existing - this allows removal of patterns
    const combined = [...new Set([...DEFAULT_STIGNORE_PATTERNS, ...patterns])];

    await writeStignore(folderPath, combined);
    return { applied: patterns.length, total: combined.length };
}
